apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: atour-backend
  name: atour-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: atour-backend
    spec:
      containers:
        - image: registry.atour-se.net/atour-se:latest
          name: atour-backend
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
