version: '3.3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  atour-backend:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app